import { Activity, Cable, Cpu, Gauge, Monitor, Radio, Router, Terminal } from 'lucide-react'
import type { ControlPlaneScenario, Workstream } from './types'

export const controlPlaneWorkstreams: Workstream[] = [
  {
    id: 'fleet',
    label: 'Fleet',
    description: 'Mock devices, severity, transport, and target identity.',
    icon: Monitor,
  },
  {
    id: 'connect',
    label: 'Connect',
    description: 'Direct HTTP, Web Serial, devd, and mock source selection.',
    icon: Cable,
  },
  {
    id: 'overview',
    label: 'Overview',
    description: 'Operator-friendly thermal, power, fan, and network state.',
    icon: Gauge,
  },
  {
    id: 'wifi',
    label: 'WiFi',
    description: 'USB-origin provisioning phases with device-reported handoff.',
    icon: Router,
  },
  {
    id: 'firmware',
    label: 'Firmware',
    description: 'Catalog compatibility, dry-run, flashing, and lock state.',
    icon: Cpu,
  },
  {
    id: 'monitor',
    label: 'Monitor',
    description: 'Bounded logs, protocol trace, and diagnostics isolation.',
    icon: Terminal,
  },
]

export const controlPlaneScenario: ControlPlaneScenario = {
  name: 'Nominal lab bench',
  headline: 'Flux Purr link tool',
  subhead:
    'A small mock-first workbench for hotplate runtime control, cooling policy, firmware dry-run, and live trace review.',
  selectedDeviceId: 'fp-lab-01',
  devices: [
    {
      id: 'fp-lab-01',
      alias: 'Bench Alpha',
      location: 'Thermal lab',
      transport: 'devd',
      severity: 'nominal',
      baseUrl: 'devd://localhost/flux-purr-alpha',
      firmware: 'fw/v0.4.0-dev',
      buildId: 's3-7f31c9',
      uptime: '03:18:42',
      boardTempC: 38.4,
      currentTempC: 183.6,
      targetTempC: 220,
      voltageMv: 20010,
      currentMa: 840,
      pdRequestMv: 20000,
      pdContractMv: 20000,
      pdState: 'ready',
      heaterOutputPercent: 22,
      activeCoolingEnabled: true,
      fanState: 'AUTO',
      wifiRssi: -54,
      networkState: 'connected',
      leaseState: 'active',
      capabilities: ['identity', 'status', 'wifi_config', 'flash', 'monitor'],
    },
    {
      id: 'fp-kit-02',
      alias: 'Field Kit',
      location: 'Bring-up cart',
      transport: 'serial',
      severity: 'warning',
      baseUrl: 'serial://usbmodem14101',
      firmware: 'fw/v0.3.1',
      buildId: 's3-2ba216',
      uptime: '00:46:05',
      boardTempC: 54.1,
      currentTempC: 286.4,
      targetTempC: 260,
      voltageMv: 12030,
      currentMa: 1180,
      pdRequestMv: 20000,
      pdContractMv: 12000,
      pdState: 'fallback_5v',
      heaterOutputPercent: 41,
      activeCoolingEnabled: true,
      fanState: 'RUN',
      wifiRssi: null,
      networkState: 'idle',
      leaseState: 'none',
      capabilities: ['identity', 'status', 'wifi_config', 'monitor'],
    },
    {
      id: 'fp-demo-03',
      alias: 'Offline Mock',
      location: 'Design review',
      transport: 'mock',
      severity: 'offline',
      baseUrl: 'mock:offline-device',
      firmware: 'fw/v0.2.0',
      buildId: 's3-mock',
      uptime: 'disconnected',
      boardTempC: 0,
      currentTempC: 0,
      targetTempC: 180,
      voltageMv: 0,
      currentMa: 0,
      pdRequestMv: 20000,
      pdContractMv: 0,
      pdState: 'fault',
      heaterOutputPercent: 0,
      activeCoolingEnabled: false,
      fanState: 'OFF',
      wifiRssi: null,
      networkState: 'disabled',
      leaseState: 'none',
      capabilities: ['identity', 'status'],
    },
  ],
  metrics: [
    {
      label: 'Bound targets',
      value: '03',
      detail: '1 devd, 1 serial, 1 mock',
      tone: 'neutral',
    },
    {
      label: 'Lease TTL',
      value: '28s',
      detail: 'heartbeat active',
      tone: 'success',
    },
    {
      label: 'Flash gate',
      value: 'Dry',
      detail: 'dry-run must pass',
      tone: 'accent',
    },
    {
      label: 'Trace buffer',
      value: '64',
      detail: 'bounded JSONL frames',
      tone: 'warning',
    },
  ],
  wifiPhases: [
    {
      label: 'USB lease',
      detail: 'Exclusive browser lease renewed by devd heartbeat.',
      state: 'done',
    },
    {
      label: 'Store credentials',
      detail: 'SSID accepted and queued for firmware handoff.',
      state: 'done',
    },
    {
      label: 'Device connecting',
      detail: 'UI waits for firmware network state, not optimistic ack.',
      state: 'active',
    },
    {
      label: 'HTTP handoff',
      detail: 'Direct target appears only after identity probe succeeds.',
      state: 'pending',
    },
  ],
  flashPhases: [
    {
      label: 'Artifact selected',
      detail: 'Target chip, protocol, feature list, and hash available.',
      state: 'done',
    },
    {
      label: 'Compatibility check',
      detail: 'Current device matches ESP32-S3 + web_serial capability.',
      state: 'done',
    },
    {
      label: 'Dry-run',
      detail: 'devd validates local files before touching flash.',
      state: 'active',
    },
    {
      label: 'Write locked',
      detail: 'Drawer closes are disabled while real flashing runs.',
      state: 'pending',
    },
  ],
  artifacts: [
    {
      id: 'web-serial-debug',
      version: 'fw/v0.4.0-dev',
      target: 'esp32s3',
      profile: 'debug + web_serial',
      compatibility: 'match',
      hash: 'sha256:7b8c...42af',
      progressPercent: 64,
      protocol: 'flux-purr.usb.v1',
      features: ['web_serial', 'monitor'],
    },
    {
      id: 'wifi-http-rc',
      version: 'fw/v0.4.0-rc.1',
      target: 'esp32s3',
      profile: 'release + net_http',
      compatibility: 'warning',
      hash: 'sha256:92da...a103',
      progressPercent: 18,
      protocol: 'flux-purr.usb.v1',
      features: ['web_serial', 'net_http'],
    },
    {
      id: 'c3-legacy',
      version: 'fw/v0.1.0',
      target: 'esp32c3',
      profile: 'legacy',
      compatibility: 'blocked',
      hash: 'sha256:0019...ee10',
      progressPercent: 0,
      protocol: 'legacy',
      features: [],
    },
  ],
  events: [
    {
      time: '20:14:03',
      source: 'devd',
      message: 'lease heartbeat accepted for Bench Alpha',
      tone: 'success',
    },
    {
      time: '20:14:06',
      source: 'usb-cdc',
      message: 'status frame decoded: temp=183.6℃ target=220℃ heater=22%',
      tone: 'info',
    },
    {
      time: '20:14:12',
      source: 'pd',
      message: 'PD contract ready at 20.0V, request remains 20.0V',
      tone: 'warning',
    },
    {
      time: '20:14:17',
      source: 'flash',
      message: 'dry-run opened artifact catalog without write access',
      tone: 'info',
    },
    {
      time: '20:14:21',
      source: 'probe',
      message: 'identity frame matched Bench Alpha capability map',
      tone: 'success',
    },
    {
      time: '20:14:24',
      source: 'monitor',
      message: 'trace frame stored in runtime buffer',
      tone: 'info',
    },
    {
      time: '20:14:29',
      source: 'thermal',
      message: 'plate sample 183.6℃, board 38.4℃, fan policy AUTO',
      tone: 'success',
    },
    {
      time: '20:14:33',
      source: 'heater',
      message: 'heater output adjusted to 22% under target ramp',
      tone: 'success',
    },
    {
      time: '20:14:39',
      source: 'flash',
      message: 'artifact hash verified against local catalog entry',
      tone: 'success',
    },
    {
      time: '20:14:45',
      source: 'devd',
      message: 'lease heartbeat renewed, next deadline in 28s',
      tone: 'info',
    },
    {
      time: '20:14:48',
      source: 'ui',
      message: 'bounded trace window rotated oldest frame out',
      tone: 'info',
    },
  ],
}

export const degradedControlPlaneScenario: ControlPlaneScenario = {
  ...controlPlaneScenario,
  name: 'Degraded transport',
  headline: 'Link needs attention',
  subhead:
    'The same small tool keeps the operator on one screen when a USB lease or WiFi handoff fails.',
  selectedDeviceId: 'fp-kit-02',
  devices: controlPlaneScenario.devices.map((device) =>
    device.id === 'fp-kit-02'
      ? {
          ...device,
          leaseState: 'conflict',
          networkState: 'timeout',
          transportIssue: 'Another browser tab owns the USB control lease.',
        }
      : device
  ),
  metrics: [
    {
      label: 'Bound targets',
      value: '02',
      detail: 'offline mock excluded',
      tone: 'warning',
    },
    {
      label: 'Lease TTL',
      value: '00s',
      detail: 'renewal conflict',
      tone: 'warning',
    },
    {
      label: 'Flash gate',
      value: 'Hold',
      detail: 'operator confirmation required',
      tone: 'accent',
    },
    {
      label: 'Trace buffer',
      value: '64',
      detail: 'oldest frames rotate out',
      tone: 'neutral',
    },
  ],
  wifiPhases: controlPlaneScenario.wifiPhases.map((phase) =>
    phase.label === 'Device connecting'
      ? {
          ...phase,
          detail: 'Firmware reports timeout while the UI keeps the last known state.',
          state: 'blocked',
        }
      : phase
  ),
  events: [
    {
      time: '20:16:31',
      source: 'lease',
      message: 'another tab owns the USB control lease',
      tone: 'danger',
    },
    {
      time: '20:16:44',
      source: 'pd',
      message: 'PD contract fell back below requested heater voltage',
      tone: 'warning',
    },
    {
      time: '20:17:02',
      source: 'monitor',
      message: 'trace buffer retained the latest 64 frames',
      tone: 'success',
    },
    {
      time: '20:17:08',
      source: 'serial',
      message: 'claim attempt deferred until lease owner releases',
      tone: 'warning',
    },
    {
      time: '20:17:14',
      source: 'thermal',
      message: 'heater output clamped while power contract is degraded',
      tone: 'info',
    },
    {
      time: '20:17:22',
      source: 'flash',
      message: 'dry-run blocked because transport is degraded',
      tone: 'danger',
    },
    {
      time: '20:17:29',
      source: 'devd',
      message: 'heartbeat missed twice, status panel stays degraded',
      tone: 'warning',
    },
    {
      time: '20:17:36',
      source: 'monitor',
      message: 'latest diagnostic frame copied to runtime log',
      tone: 'info',
    },
  ],
}

export const transportIcons = {
  http: Radio,
  serial: Cable,
  devd: Activity,
  mock: Monitor,
}
