import { Activity, Cable, Cpu, Gauge, Monitor, Radio, Router, Terminal } from 'lucide-react'
import type { ControlPlaneScenario, Workstream } from './types'

export const controlPlaneWorkstreams: Workstream[] = [
  {
    id: 'fleet',
    label: 'Fleet',
    description: 'Mock devices, severity, transport, and target identity.',
    icon: Monitor,
  },
  {
    id: 'connect',
    label: 'Connect',
    description: 'Direct HTTP, Web Serial, devd, and mock source selection.',
    icon: Cable,
  },
  {
    id: 'overview',
    label: 'Overview',
    description: 'Operator-friendly thermal, power, fan, and network state.',
    icon: Gauge,
  },
  {
    id: 'wifi',
    label: 'WiFi',
    description: 'USB-origin provisioning phases with device-reported handoff.',
    icon: Router,
  },
  {
    id: 'firmware',
    label: 'Firmware',
    description: 'Catalog compatibility, dry-run, flashing, and lock state.',
    icon: Cpu,
  },
  {
    id: 'monitor',
    label: 'Monitor',
    description: 'Bounded logs, protocol trace, and diagnostics isolation.',
    icon: Terminal,
  },
]

export const controlPlaneScenario: ControlPlaneScenario = {
  name: '标准实验台',
  headline: 'Flux Purr 连接控制台',
  subhead:
    '一个以模拟数据优先的小型工作台，用于热板运行控制、散热策略、固件空跑检查和实时追踪查看。',
  selectedDeviceId: 'fp-lab-01',
  devices: [
    {
      id: 'fp-lab-01',
      alias: '基准治具 A',
      location: '模拟热控实验台',
      transport: 'mock',
      severity: 'nominal',
      baseUrl: 'mock:bench-alpha',
      firmware: 'fw/v0.4.0-dev',
      buildId: 's3-7f31c9',
      uptime: '03:18:42',
      boardTempC: 38.4,
      currentTempC: 183.6,
      targetTempC: 220,
      voltageMv: 20010,
      currentMa: 840,
      pdRequestMv: 20000,
      pdContractMv: 20000,
      pdState: 'ready',
      manualPpsEnabled: false,
      manualPpsMv: null,
      manualPpsMa: null,
      ppsCapabilityMinMv: 5000,
      ppsCapabilityMaxMv: 21000,
      ppsCapabilityMaxMa: 3000,
      manualPpsError: null,
      calibration: {
        mode: 'off',
        ppsEnabled: false,
        ppsMv: null,
        ppsMa: null,
        heaterEnabled: false,
        targetAdcMv: null,
        stable: false,
        stabilityErrorMv: null,
        error: null,
        job: {
          kind: null,
          status: 'idle',
          progressPercent: 0,
          samplesCollected: 0,
          nextRequestMv: null,
          message: null,
        },
      },
      heaterEnabled: true,
      heaterOutputPercent: 22,
      activeCoolingEnabled: true,
      fanState: 'AUTO',
      wifiRssi: -54,
      networkState: 'connected',
      leaseState: 'none',
      capabilities: ['identity', 'status', 'wifi_config', 'flash', 'monitor'],
    },
    {
      id: 'fp-kit-02',
      alias: '现场工具箱',
      location: 'Bring-up 推车',
      transport: 'serial',
      severity: 'warning',
      baseUrl: 'serial://usbmodem14101',
      firmware: 'fw/v0.3.1',
      buildId: 's3-2ba216',
      uptime: '00:46:05',
      boardTempC: 54.1,
      currentTempC: 286.4,
      targetTempC: 260,
      voltageMv: 12030,
      currentMa: 1180,
      pdRequestMv: 20000,
      pdContractMv: 12000,
      pdState: 'fallback_5v',
      manualPpsEnabled: true,
      manualPpsMv: 12000,
      manualPpsMa: 2500,
      ppsCapabilityMinMv: 5000,
      ppsCapabilityMaxMv: 15000,
      ppsCapabilityMaxMa: 3000,
      manualPpsError: null,
      calibration: {
        mode: 'off',
        ppsEnabled: false,
        ppsMv: null,
        ppsMa: null,
        heaterEnabled: false,
        targetAdcMv: null,
        stable: false,
        stabilityErrorMv: null,
        error: null,
        job: {
          kind: null,
          status: 'idle',
          progressPercent: 0,
          samplesCollected: 0,
          nextRequestMv: null,
          message: null,
        },
      },
      heaterEnabled: true,
      heaterOutputPercent: 41,
      activeCoolingEnabled: true,
      fanState: 'RUN',
      wifiRssi: null,
      networkState: 'idle',
      leaseState: 'none',
      capabilities: ['identity', 'status', 'wifi_config', 'monitor'],
    },
    {
      id: 'fp-demo-03',
      alias: '离线模拟设备',
      location: '设计评审',
      transport: 'mock',
      severity: 'offline',
      baseUrl: 'mock:offline-device',
      firmware: 'fw/v0.2.0',
      buildId: 's3-mock',
      uptime: 'disconnected',
      boardTempC: 0,
      currentTempC: 0,
      targetTempC: 180,
      voltageMv: 0,
      currentMa: 0,
      pdRequestMv: 20000,
      pdContractMv: 0,
      pdState: 'fault',
      manualPpsEnabled: false,
      manualPpsMv: null,
      manualPpsMa: null,
      ppsCapabilityMinMv: null,
      ppsCapabilityMaxMv: null,
      ppsCapabilityMaxMa: null,
      manualPpsError: 'manual_pps_no_capability',
      calibration: {
        mode: 'off',
        ppsEnabled: false,
        ppsMv: null,
        ppsMa: null,
        heaterEnabled: false,
        targetAdcMv: null,
        stable: false,
        stabilityErrorMv: null,
        error: null,
        job: {
          kind: null,
          status: 'idle',
          progressPercent: 0,
          samplesCollected: 0,
          nextRequestMv: null,
          message: null,
        },
      },
      heaterEnabled: false,
      heaterOutputPercent: 0,
      activeCoolingEnabled: false,
      fanState: 'OFF',
      wifiRssi: null,
      networkState: 'disabled',
      leaseState: 'none',
      capabilities: ['identity', 'status'],
    },
  ],
  metrics: [
    {
      label: '已绑定目标',
      value: '03',
      detail: '仅模拟治具',
      tone: 'neutral',
    },
    {
      label: '租约剩余',
      value: '28s',
      detail: '心跳活跃',
      tone: 'success',
    },
    {
      label: '烧录门禁',
      value: '空跑',
      detail: '必须先通过空跑检查',
      tone: 'accent',
    },
    {
      label: '追踪缓冲',
      value: '64',
      detail: 'JSONL 帧有界缓存',
      tone: 'warning',
    },
  ],
  wifiPhases: [
    {
      label: 'USB lease',
      detail: 'Exclusive browser lease renewed by devd heartbeat.',
      state: 'done',
    },
    {
      label: 'Store credentials',
      detail: 'SSID accepted and queued for firmware handoff.',
      state: 'done',
    },
    {
      label: 'Device connecting',
      detail: 'UI waits for firmware network state, not optimistic ack.',
      state: 'active',
    },
    {
      label: 'HTTP handoff',
      detail: 'Direct target appears only after identity probe succeeds.',
      state: 'pending',
    },
  ],
  flashPhases: [
    {
      label: 'Artifact selected',
      detail: 'Target chip, protocol, feature list, and hash available.',
      state: 'done',
    },
    {
      label: 'Compatibility check',
      detail: 'Current device matches ESP32-S3 + web_serial capability.',
      state: 'done',
    },
    {
      label: 'Dry-run',
      detail: 'devd validates local files before touching flash.',
      state: 'active',
    },
    {
      label: 'Write locked',
      detail: 'Drawer closes are disabled while real flashing runs.',
      state: 'pending',
    },
  ],
  artifacts: [
    {
      id: 'web-serial-debug',
      version: 'fw/v0.4.0-dev',
      target: 'esp32s3',
      profile: 'debug + web_serial',
      compatibility: 'match',
      hash: 'sha256:7b8c...42af',
      progressPercent: 64,
      protocol: 'flux-purr.usb.v1',
      features: ['web_serial', 'monitor'],
    },
    {
      id: 'wifi-http-rc',
      version: 'fw/v0.4.0-rc.1',
      target: 'esp32s3',
      profile: 'release + direct HTTP planned',
      compatibility: 'warning',
      hash: 'sha256:92da...a103',
      progressPercent: 18,
      protocol: 'flux-purr.usb.v1',
      features: ['web_serial'],
    },
    {
      id: 'c3-legacy',
      version: 'fw/v0.1.0',
      target: 'esp32c3',
      profile: 'legacy',
      compatibility: 'blocked',
      hash: 'sha256:0019...ee10',
      progressPercent: 0,
      protocol: 'legacy',
      features: [],
    },
  ],
  events: [
    {
      time: '20:14:03',
      source: '模拟',
      message: '已载入治具运行时样本',
      tone: 'success',
    },
    {
      time: '20:14:06',
      source: 'usb-cdc',
      message: '已解码状态帧：温度 183.6℃ / 目标 220℃ / 加热 22%',
      tone: 'info',
    },
    {
      time: '20:14:12',
      source: 'pd',
      message: 'PD 合约已就绪：20.0V，申请值保持 20.0V',
      tone: 'warning',
    },
    {
      time: '20:14:17',
      source: 'flash',
      message: '空跑已打开制品目录，未进行写入',
      tone: 'info',
    },
    {
      time: '20:14:21',
      source: 'probe',
      message: '身份帧已匹配基准治具 A 能力图谱',
      tone: 'success',
    },
    {
      time: '20:14:24',
      source: 'monitor',
      message: '追踪帧已写入运行时缓冲区',
      tone: 'info',
    },
    {
      time: '20:14:29',
      source: 'thermal',
      message: '热板 183.6℃，板载 38.4℃，风扇策略自动',
      tone: 'success',
    },
    {
      time: '20:14:33',
      source: 'heater',
      message: '加热输出已调到 22%，正在跟随目标爬升',
      tone: 'success',
    },
    {
      time: '20:14:39',
      source: 'flash',
      message: '制品哈希已与本地目录条目校验一致',
      tone: 'success',
    },
    {
      time: '20:14:45',
      source: 'devd',
      message: '租约心跳已续期，下次截止还有 28 秒',
      tone: 'info',
    },
    {
      time: '20:14:48',
      source: 'ui',
      message: '有界追踪窗口已滚出最旧帧',
      tone: 'info',
    },
  ],
}

export const degradedControlPlaneScenario: ControlPlaneScenario = {
  ...controlPlaneScenario,
  name: 'Degraded transport',
  headline: 'Link needs attention',
  subhead:
    'The same small tool keeps the operator on one screen when a USB lease or WiFi handoff fails.',
  selectedDeviceId: 'fp-kit-02',
  devices: controlPlaneScenario.devices.map((device) =>
    device.id === 'fp-kit-02'
      ? {
          ...device,
          leaseState: 'conflict',
          networkState: 'timeout',
          transportIssue: 'Another browser tab owns the USB control lease.',
        }
      : device
  ),
  metrics: [
    {
      label: 'Bound targets',
      value: '02',
      detail: 'offline mock excluded',
      tone: 'warning',
    },
    {
      label: 'Lease TTL',
      value: '00s',
      detail: 'renewal conflict',
      tone: 'warning',
    },
    {
      label: 'Flash gate',
      value: 'Hold',
      detail: 'operator confirmation required',
      tone: 'accent',
    },
    {
      label: 'Trace buffer',
      value: '64',
      detail: 'oldest frames rotate out',
      tone: 'neutral',
    },
  ],
  wifiPhases: controlPlaneScenario.wifiPhases.map((phase) =>
    phase.label === 'Device connecting'
      ? {
          ...phase,
          detail: 'Firmware reports timeout while the UI keeps the last known state.',
          state: 'blocked',
        }
      : phase
  ),
  events: [
    {
      time: '20:16:31',
      source: 'lease',
      message: 'another tab owns the USB control lease',
      tone: 'danger',
    },
    {
      time: '20:16:44',
      source: 'pd',
      message: 'PD contract fell back below requested heater voltage',
      tone: 'warning',
    },
    {
      time: '20:17:02',
      source: 'monitor',
      message: 'trace buffer retained the latest 64 frames',
      tone: 'success',
    },
    {
      time: '20:17:08',
      source: 'serial',
      message: 'claim attempt deferred until lease owner releases',
      tone: 'warning',
    },
    {
      time: '20:17:14',
      source: 'thermal',
      message: 'heater output clamped while power contract is degraded',
      tone: 'info',
    },
    {
      time: '20:17:22',
      source: 'flash',
      message: 'dry-run blocked because transport is degraded',
      tone: 'danger',
    },
    {
      time: '20:17:29',
      source: 'devd',
      message: 'heartbeat missed twice, status panel stays degraded',
      tone: 'warning',
    },
    {
      time: '20:17:36',
      source: 'monitor',
      message: 'latest diagnostic frame copied to runtime log',
      tone: 'info',
    },
  ],
}

export const transportIcons = {
  http: Radio,
  serial: Cable,
  devd: Activity,
  mock: Monitor,
}
