[project]
id = "flux-purr-80d2"

[agentd]
auto_start_daemon = true
tail_default = 200

[mcu.esp32s3_frontpanel]
backend = "espflash"
chip = "esp32s3"
artifact_elf = "firmware/target/xtensa-esp32s3-none-elf/release/esp32s3-fan-cycle"

[mcu.esp32s3_frontpanel.espflash]
log_format = "defmt"
after_flash = "no-reset"
skip_update_check = true
