/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConsoleRouteImport } from './routes/_console'
import { Route as ConsoleIndexRouteImport } from './routes/_console.index'
import { Route as ConsoleDevicesIndexRouteImport } from './routes/_console.devices.index'
import { Route as ConsoleDevicesNewRouteImport } from './routes/_console.devices.new'
import { Route as ConsoleDevicesDeviceIdIndexRouteImport } from './routes/_console.devices.$deviceId.index'
import { Route as ConsoleDevicesDeviceIdOverviewRouteImport } from './routes/_console.devices.$deviceId.overview'
import { Route as ConsoleDevicesDeviceIdSettingsRouteImport } from './routes/_console.devices.$deviceId.settings'
import { Route as ConsoleDevicesDeviceIdUpdateRouteImport } from './routes/_console.devices.$deviceId.update'
import { Route as ConsoleDevicesDeviceIdCalibrationIndexRouteImport } from './routes/_console.devices.$deviceId.calibration.index'
import { Route as ConsoleDevicesDeviceIdCalibrationHeaterCurveRouteImport } from './routes/_console.devices.$deviceId.calibration.heater-curve'
import { Route as ConsoleDevicesDeviceIdCalibrationRtdAdcRouteImport } from './routes/_console.devices.$deviceId.calibration.rtd-adc'
import { Route as ConsoleDevicesDeviceIdCalibrationVinAdcRouteImport } from './routes/_console.devices.$deviceId.calibration.vin-adc'
import { Route as ConsoleDevicesDeviceIdSettingsFanRouteImport } from './routes/_console.devices.$deviceId.settings.fan'
import { Route as ConsoleDevicesDeviceIdSettingsPresetsRouteImport } from './routes/_console.devices.$deviceId.settings.presets'
import { Route as ConsoleDevicesDeviceIdSettingsWifiRouteImport } from './routes/_console.devices.$deviceId.settings.wifi'

const ConsoleRoute = ConsoleRouteImport.update({
  id: '/_console',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleDevicesIndexRoute = ConsoleDevicesIndexRouteImport.update({
  id: '/devices/',
  path: '/devices/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleDevicesNewRoute = ConsoleDevicesNewRouteImport.update({
  id: '/devices/new',
  path: '/devices/new',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleDevicesDeviceIdIndexRoute =
  ConsoleDevicesDeviceIdIndexRouteImport.update({
    id: '/devices/$deviceId/',
    path: '/devices/$deviceId/',
    getParentRoute: () => ConsoleRoute,
  } as any)
const ConsoleDevicesDeviceIdOverviewRoute =
  ConsoleDevicesDeviceIdOverviewRouteImport.update({
    id: '/devices/$deviceId/overview',
    path: '/devices/$deviceId/overview',
    getParentRoute: () => ConsoleRoute,
  } as any)
const ConsoleDevicesDeviceIdSettingsRoute =
  ConsoleDevicesDeviceIdSettingsRouteImport.update({
    id: '/devices/$deviceId/settings',
    path: '/devices/$deviceId/settings',
    getParentRoute: () => ConsoleRoute,
  } as any)
const ConsoleDevicesDeviceIdUpdateRoute =
  ConsoleDevicesDeviceIdUpdateRouteImport.update({
    id: '/devices/$deviceId/update',
    path: '/devices/$deviceId/update',
    getParentRoute: () => ConsoleRoute,
  } as any)
const ConsoleDevicesDeviceIdCalibrationIndexRoute =
  ConsoleDevicesDeviceIdCalibrationIndexRouteImport.update({
    id: '/devices/$deviceId/calibration/',
    path: '/devices/$deviceId/calibration/',
    getParentRoute: () => ConsoleRoute,
  } as any)
const ConsoleDevicesDeviceIdCalibrationHeaterCurveRoute =
  ConsoleDevicesDeviceIdCalibrationHeaterCurveRouteImport.update({
    id: '/devices/$deviceId/calibration/heater-curve',
    path: '/devices/$deviceId/calibration/heater-curve',
    getParentRoute: () => ConsoleRoute,
  } as any)
const ConsoleDevicesDeviceIdCalibrationRtdAdcRoute =
  ConsoleDevicesDeviceIdCalibrationRtdAdcRouteImport.update({
    id: '/devices/$deviceId/calibration/rtd-adc',
    path: '/devices/$deviceId/calibration/rtd-adc',
    getParentRoute: () => ConsoleRoute,
  } as any)
const ConsoleDevicesDeviceIdCalibrationVinAdcRoute =
  ConsoleDevicesDeviceIdCalibrationVinAdcRouteImport.update({
    id: '/devices/$deviceId/calibration/vin-adc',
    path: '/devices/$deviceId/calibration/vin-adc',
    getParentRoute: () => ConsoleRoute,
  } as any)
const ConsoleDevicesDeviceIdSettingsFanRoute =
  ConsoleDevicesDeviceIdSettingsFanRouteImport.update({
    id: '/fan',
    path: '/fan',
    getParentRoute: () => ConsoleDevicesDeviceIdSettingsRoute,
  } as any)
const ConsoleDevicesDeviceIdSettingsPresetsRoute =
  ConsoleDevicesDeviceIdSettingsPresetsRouteImport.update({
    id: '/presets',
    path: '/presets',
    getParentRoute: () => ConsoleDevicesDeviceIdSettingsRoute,
  } as any)
const ConsoleDevicesDeviceIdSettingsWifiRoute =
  ConsoleDevicesDeviceIdSettingsWifiRouteImport.update({
    id: '/wifi',
    path: '/wifi',
    getParentRoute: () => ConsoleDevicesDeviceIdSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ConsoleIndexRoute
  '/devices/new': typeof ConsoleDevicesNewRoute
  '/devices/': typeof ConsoleDevicesIndexRoute
  '/devices/$deviceId/overview': typeof ConsoleDevicesDeviceIdOverviewRoute
  '/devices/$deviceId/settings': typeof ConsoleDevicesDeviceIdSettingsRouteWithChildren
  '/devices/$deviceId/update': typeof ConsoleDevicesDeviceIdUpdateRoute
  '/devices/$deviceId/': typeof ConsoleDevicesDeviceIdIndexRoute
  '/devices/$deviceId/calibration/heater-curve': typeof ConsoleDevicesDeviceIdCalibrationHeaterCurveRoute
  '/devices/$deviceId/calibration/rtd-adc': typeof ConsoleDevicesDeviceIdCalibrationRtdAdcRoute
  '/devices/$deviceId/calibration/vin-adc': typeof ConsoleDevicesDeviceIdCalibrationVinAdcRoute
  '/devices/$deviceId/settings/fan': typeof ConsoleDevicesDeviceIdSettingsFanRoute
  '/devices/$deviceId/settings/presets': typeof ConsoleDevicesDeviceIdSettingsPresetsRoute
  '/devices/$deviceId/settings/wifi': typeof ConsoleDevicesDeviceIdSettingsWifiRoute
  '/devices/$deviceId/calibration/': typeof ConsoleDevicesDeviceIdCalibrationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ConsoleIndexRoute
  '/devices/new': typeof ConsoleDevicesNewRoute
  '/devices': typeof ConsoleDevicesIndexRoute
  '/devices/$deviceId/overview': typeof ConsoleDevicesDeviceIdOverviewRoute
  '/devices/$deviceId/settings': typeof ConsoleDevicesDeviceIdSettingsRouteWithChildren
  '/devices/$deviceId/update': typeof ConsoleDevicesDeviceIdUpdateRoute
  '/devices/$deviceId': typeof ConsoleDevicesDeviceIdIndexRoute
  '/devices/$deviceId/calibration/heater-curve': typeof ConsoleDevicesDeviceIdCalibrationHeaterCurveRoute
  '/devices/$deviceId/calibration/rtd-adc': typeof ConsoleDevicesDeviceIdCalibrationRtdAdcRoute
  '/devices/$deviceId/calibration/vin-adc': typeof ConsoleDevicesDeviceIdCalibrationVinAdcRoute
  '/devices/$deviceId/settings/fan': typeof ConsoleDevicesDeviceIdSettingsFanRoute
  '/devices/$deviceId/settings/presets': typeof ConsoleDevicesDeviceIdSettingsPresetsRoute
  '/devices/$deviceId/settings/wifi': typeof ConsoleDevicesDeviceIdSettingsWifiRoute
  '/devices/$deviceId/calibration': typeof ConsoleDevicesDeviceIdCalibrationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_console': typeof ConsoleRouteWithChildren
  '/_console/': typeof ConsoleIndexRoute
  '/_console/devices/new': typeof ConsoleDevicesNewRoute
  '/_console/devices/': typeof ConsoleDevicesIndexRoute
  '/_console/devices/$deviceId/overview': typeof ConsoleDevicesDeviceIdOverviewRoute
  '/_console/devices/$deviceId/settings': typeof ConsoleDevicesDeviceIdSettingsRouteWithChildren
  '/_console/devices/$deviceId/update': typeof ConsoleDevicesDeviceIdUpdateRoute
  '/_console/devices/$deviceId/': typeof ConsoleDevicesDeviceIdIndexRoute
  '/_console/devices/$deviceId/calibration/heater-curve': typeof ConsoleDevicesDeviceIdCalibrationHeaterCurveRoute
  '/_console/devices/$deviceId/calibration/rtd-adc': typeof ConsoleDevicesDeviceIdCalibrationRtdAdcRoute
  '/_console/devices/$deviceId/calibration/vin-adc': typeof ConsoleDevicesDeviceIdCalibrationVinAdcRoute
  '/_console/devices/$deviceId/settings/fan': typeof ConsoleDevicesDeviceIdSettingsFanRoute
  '/_console/devices/$deviceId/settings/presets': typeof ConsoleDevicesDeviceIdSettingsPresetsRoute
  '/_console/devices/$deviceId/settings/wifi': typeof ConsoleDevicesDeviceIdSettingsWifiRoute
  '/_console/devices/$deviceId/calibration/': typeof ConsoleDevicesDeviceIdCalibrationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/devices/new'
    | '/devices/'
    | '/devices/$deviceId/overview'
    | '/devices/$deviceId/settings'
    | '/devices/$deviceId/update'
    | '/devices/$deviceId/'
    | '/devices/$deviceId/calibration/heater-curve'
    | '/devices/$deviceId/calibration/rtd-adc'
    | '/devices/$deviceId/calibration/vin-adc'
    | '/devices/$deviceId/settings/fan'
    | '/devices/$deviceId/settings/presets'
    | '/devices/$deviceId/settings/wifi'
    | '/devices/$deviceId/calibration/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/devices/new'
    | '/devices'
    | '/devices/$deviceId/overview'
    | '/devices/$deviceId/settings'
    | '/devices/$deviceId/update'
    | '/devices/$deviceId'
    | '/devices/$deviceId/calibration/heater-curve'
    | '/devices/$deviceId/calibration/rtd-adc'
    | '/devices/$deviceId/calibration/vin-adc'
    | '/devices/$deviceId/settings/fan'
    | '/devices/$deviceId/settings/presets'
    | '/devices/$deviceId/settings/wifi'
    | '/devices/$deviceId/calibration'
  id:
    | '__root__'
    | '/_console'
    | '/_console/'
    | '/_console/devices/new'
    | '/_console/devices/'
    | '/_console/devices/$deviceId/overview'
    | '/_console/devices/$deviceId/settings'
    | '/_console/devices/$deviceId/update'
    | '/_console/devices/$deviceId/'
    | '/_console/devices/$deviceId/calibration/heater-curve'
    | '/_console/devices/$deviceId/calibration/rtd-adc'
    | '/_console/devices/$deviceId/calibration/vin-adc'
    | '/_console/devices/$deviceId/settings/fan'
    | '/_console/devices/$deviceId/settings/presets'
    | '/_console/devices/$deviceId/settings/wifi'
    | '/_console/devices/$deviceId/calibration/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ConsoleRoute: typeof ConsoleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_console': {
      id: '/_console'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/': {
      id: '/_console/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/devices/': {
      id: '/_console/devices/'
      path: '/devices'
      fullPath: '/devices/'
      preLoaderRoute: typeof ConsoleDevicesIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/devices/new': {
      id: '/_console/devices/new'
      path: '/devices/new'
      fullPath: '/devices/new'
      preLoaderRoute: typeof ConsoleDevicesNewRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/devices/$deviceId/': {
      id: '/_console/devices/$deviceId/'
      path: '/devices/$deviceId'
      fullPath: '/devices/$deviceId/'
      preLoaderRoute: typeof ConsoleDevicesDeviceIdIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/devices/$deviceId/overview': {
      id: '/_console/devices/$deviceId/overview'
      path: '/devices/$deviceId/overview'
      fullPath: '/devices/$deviceId/overview'
      preLoaderRoute: typeof ConsoleDevicesDeviceIdOverviewRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/devices/$deviceId/settings': {
      id: '/_console/devices/$deviceId/settings'
      path: '/devices/$deviceId/settings'
      fullPath: '/devices/$deviceId/settings'
      preLoaderRoute: typeof ConsoleDevicesDeviceIdSettingsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/devices/$deviceId/update': {
      id: '/_console/devices/$deviceId/update'
      path: '/devices/$deviceId/update'
      fullPath: '/devices/$deviceId/update'
      preLoaderRoute: typeof ConsoleDevicesDeviceIdUpdateRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/devices/$deviceId/calibration/': {
      id: '/_console/devices/$deviceId/calibration/'
      path: '/devices/$deviceId/calibration'
      fullPath: '/devices/$deviceId/calibration/'
      preLoaderRoute: typeof ConsoleDevicesDeviceIdCalibrationIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/devices/$deviceId/calibration/heater-curve': {
      id: '/_console/devices/$deviceId/calibration/heater-curve'
      path: '/devices/$deviceId/calibration/heater-curve'
      fullPath: '/devices/$deviceId/calibration/heater-curve'
      preLoaderRoute: typeof ConsoleDevicesDeviceIdCalibrationHeaterCurveRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/devices/$deviceId/calibration/rtd-adc': {
      id: '/_console/devices/$deviceId/calibration/rtd-adc'
      path: '/devices/$deviceId/calibration/rtd-adc'
      fullPath: '/devices/$deviceId/calibration/rtd-adc'
      preLoaderRoute: typeof ConsoleDevicesDeviceIdCalibrationRtdAdcRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/devices/$deviceId/calibration/vin-adc': {
      id: '/_console/devices/$deviceId/calibration/vin-adc'
      path: '/devices/$deviceId/calibration/vin-adc'
      fullPath: '/devices/$deviceId/calibration/vin-adc'
      preLoaderRoute: typeof ConsoleDevicesDeviceIdCalibrationVinAdcRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/devices/$deviceId/settings/fan': {
      id: '/_console/devices/$deviceId/settings/fan'
      path: '/fan'
      fullPath: '/devices/$deviceId/settings/fan'
      preLoaderRoute: typeof ConsoleDevicesDeviceIdSettingsFanRouteImport
      parentRoute: typeof ConsoleDevicesDeviceIdSettingsRoute
    }
    '/_console/devices/$deviceId/settings/presets': {
      id: '/_console/devices/$deviceId/settings/presets'
      path: '/presets'
      fullPath: '/devices/$deviceId/settings/presets'
      preLoaderRoute: typeof ConsoleDevicesDeviceIdSettingsPresetsRouteImport
      parentRoute: typeof ConsoleDevicesDeviceIdSettingsRoute
    }
    '/_console/devices/$deviceId/settings/wifi': {
      id: '/_console/devices/$deviceId/settings/wifi'
      path: '/wifi'
      fullPath: '/devices/$deviceId/settings/wifi'
      preLoaderRoute: typeof ConsoleDevicesDeviceIdSettingsWifiRouteImport
      parentRoute: typeof ConsoleDevicesDeviceIdSettingsRoute
    }
  }
}

interface ConsoleDevicesDeviceIdSettingsRouteChildren {
  ConsoleDevicesDeviceIdSettingsFanRoute: typeof ConsoleDevicesDeviceIdSettingsFanRoute
  ConsoleDevicesDeviceIdSettingsPresetsRoute: typeof ConsoleDevicesDeviceIdSettingsPresetsRoute
  ConsoleDevicesDeviceIdSettingsWifiRoute: typeof ConsoleDevicesDeviceIdSettingsWifiRoute
}

const ConsoleDevicesDeviceIdSettingsRouteChildren: ConsoleDevicesDeviceIdSettingsRouteChildren =
  {
    ConsoleDevicesDeviceIdSettingsFanRoute:
      ConsoleDevicesDeviceIdSettingsFanRoute,
    ConsoleDevicesDeviceIdSettingsPresetsRoute:
      ConsoleDevicesDeviceIdSettingsPresetsRoute,
    ConsoleDevicesDeviceIdSettingsWifiRoute:
      ConsoleDevicesDeviceIdSettingsWifiRoute,
  }

const ConsoleDevicesDeviceIdSettingsRouteWithChildren =
  ConsoleDevicesDeviceIdSettingsRoute._addFileChildren(
    ConsoleDevicesDeviceIdSettingsRouteChildren,
  )

interface ConsoleRouteChildren {
  ConsoleIndexRoute: typeof ConsoleIndexRoute
  ConsoleDevicesNewRoute: typeof ConsoleDevicesNewRoute
  ConsoleDevicesIndexRoute: typeof ConsoleDevicesIndexRoute
  ConsoleDevicesDeviceIdOverviewRoute: typeof ConsoleDevicesDeviceIdOverviewRoute
  ConsoleDevicesDeviceIdSettingsRoute: typeof ConsoleDevicesDeviceIdSettingsRouteWithChildren
  ConsoleDevicesDeviceIdUpdateRoute: typeof ConsoleDevicesDeviceIdUpdateRoute
  ConsoleDevicesDeviceIdIndexRoute: typeof ConsoleDevicesDeviceIdIndexRoute
  ConsoleDevicesDeviceIdCalibrationHeaterCurveRoute: typeof ConsoleDevicesDeviceIdCalibrationHeaterCurveRoute
  ConsoleDevicesDeviceIdCalibrationRtdAdcRoute: typeof ConsoleDevicesDeviceIdCalibrationRtdAdcRoute
  ConsoleDevicesDeviceIdCalibrationVinAdcRoute: typeof ConsoleDevicesDeviceIdCalibrationVinAdcRoute
  ConsoleDevicesDeviceIdCalibrationIndexRoute: typeof ConsoleDevicesDeviceIdCalibrationIndexRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleIndexRoute: ConsoleIndexRoute,
  ConsoleDevicesNewRoute: ConsoleDevicesNewRoute,
  ConsoleDevicesIndexRoute: ConsoleDevicesIndexRoute,
  ConsoleDevicesDeviceIdOverviewRoute: ConsoleDevicesDeviceIdOverviewRoute,
  ConsoleDevicesDeviceIdSettingsRoute:
    ConsoleDevicesDeviceIdSettingsRouteWithChildren,
  ConsoleDevicesDeviceIdUpdateRoute: ConsoleDevicesDeviceIdUpdateRoute,
  ConsoleDevicesDeviceIdIndexRoute: ConsoleDevicesDeviceIdIndexRoute,
  ConsoleDevicesDeviceIdCalibrationHeaterCurveRoute:
    ConsoleDevicesDeviceIdCalibrationHeaterCurveRoute,
  ConsoleDevicesDeviceIdCalibrationRtdAdcRoute:
    ConsoleDevicesDeviceIdCalibrationRtdAdcRoute,
  ConsoleDevicesDeviceIdCalibrationVinAdcRoute:
    ConsoleDevicesDeviceIdCalibrationVinAdcRoute,
  ConsoleDevicesDeviceIdCalibrationIndexRoute:
    ConsoleDevicesDeviceIdCalibrationIndexRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ConsoleRoute: ConsoleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
